export const INIT = 'carta/Quest/INIT'

export const TYPE_SEARCH_EXP_CHANGE = 'carta/Quest/TYPE_SEARCH_EXP_CHANGE'
export const DESCRIPTIVE_SEARCH_EXP_CHANGE = 'carta/Quest/DESCRIPTIVE_SEARCH_EXP_CHANGE'
export const UPDATE_EXPAND = 'carta/Quest/UPDATE_EXPAND'

export const SET_QUEST = 'carta/Quest/SET_QUEST'
export const SET_URL_ENTERED_QUEST = 'carta/Quest/SET_URL_ENTERED_QUEST'

export const SET_PANEL_STATE = 'carta/Quest/SET_PANEL_STATE'

export const GET_QUESTINFO_REQUEST = 'carta/Quest/GET_QUESTINFO_REQUEST'
export const GET_QUESTINFO_SUCCESS = 'carta/Quest/GET_QUESTINFO_SUCCESS'
export const GET_QUESTINFO_FAIL = 'carta/Quest/GET_QUESTINFO_FAIL'

export const GET_RECOMMENDATION_REQUEST = 'carta/Quest/GET_RECOMMENDATION_REQUEST'
export const GET_RECOMMENDATION_SUCCESS = 'carta/Quest/GET_RECOMMENDATION_SUCCESS'
export const GET_RECOMMENDATION_FAIL = 'carta/Quest/GET_RECOMMENDATION_FAIL'

export const GET_DESCRIPTIVES_REQUEST = 'carta/Quest/GET_DESCRIPTIVES_REQUEST'
export const GET_DESCRIPTIVES_SUCCESS = 'carta/Quest/GET_DESCRIPTIVES_SUCCESS'
export const GET_DESCRIPTIVES_FAIL = 'carta/Quest/GET_DESCRIPTIVES_FAIL'
