export const INIT = 'carta/App/INIT'

export const SIGNIN_USER_REQUEST = 'carta/App/SIGNIN_USER_REQUEST'
export const SIGNIN_USER_SUCCESS = 'carta/App/SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_FAIL = 'carta/App/SIGNIN_USER_FAIL'

export const SIGNOUT_USER = 'carta/App/SIGNOUT_USER'

export const REGISTER_USER_REQUEST = 'carta/App/REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'carta/App/REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'carta/App/REGISTER_USER_FAIL'

export const VERIFY_USER_REQUEST = 'carta/App/VERIFY_USER_REQUEST'
export const VERIFY_USER_SUCCESS = 'carta/App/VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAIL = 'carta/App/VERIFY_USER_FAIL'

export const DELETE_USER_REQUEST = 'carta/App/DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'carta/App/DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'carta/App/DELETE_USER_FAIL'

export const UPDATE_USER_REQUEST = 'carta/App/UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'carta/App/UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'carta/App/UPDATE_USER_FAIL'

export const GET_USER_WISHLIST_REQUEST = 'carta/App/GET_USER_WISHLIST_REQUEST'
export const GET_USER_WISHLIST_SUCCESS = 'carta/App/GET_USER_WISHLIST_SUCCESS'
export const GET_USER_WISHLIST_FAIL = 'carta/App/GET_USER_WISHLIST_FAIL'

export const CREATE_USER_WISHLIST_REQUEST = 'carta/App/CREATE_USER_WISHLIST_REQUEST'
export const CREATE_USER_WISHLIST_SUCCESS = 'carta/App/CREATE_USER_WISHLIST_SUCCESS'
export const CREATE_USER_WISHLIST_FAIL = 'carta/App/CREATE_USER_WISHLIST_FAIL'

export const DELETE_USER_WISHLIST_REQUEST = 'carta/App/DELETE_USER_WISHLIST_REQUEST'
export const DELETE_USER_WISHLIST_SUCCESS = 'carta/App/DELETE_USER_WISHLIST_SUCCESS'
export const DELETE_USER_WISHLIST_FAIL = 'carta/App/DELETE_USER_WISHLIST_FAIL'

export const CHANGE_AUTH_METHOD = 'carta/App/CHANGE_AUTH_METHOD'

export const TOGGLE_MENU = 'carta/App/TOGGLE_MENU'
